name: Destroying ECR And ECS Resources

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: CD into ECR directory and destroy the ECR resources
        run: |
          cd ECR
          terraform destroy -auto-approve

      - name: CD into ECS directory and destroy the ECS
        run: |
          cd ..
          cd ECS
          terraform destroy -auto-approve

