name: Creating ECR Repository and Pushing Dcoker Image to ECR repo

on:
  push:
    branches:
      - main

jobs:
  creation_of_ecr_repo:
    name: Creating ECR Repo
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          cd ECR 
          terraform init

      - name: Terraform Plan
        run: |
          cd ECR 
          terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: | 
          cd ECR
          terraform apply -auto-approve -input=false

  build:
    name: Building Docker And Pushing Docker Image To AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build a Docker image
        run: |
          cd Image 
          docker build -t awsecrimage:latest .

      - name: Tag the Docker image
        run: |
          cd Image
          docker tag awsecrimage:latest ${{ secrets.ECR_REGISTRY }}

      - name: Push Docker image to AWS ECR
        run: |
          cd Image 
          docker push awsecrimage ${{ secrets.ECR_REGISTRY }}


    
