name: Deploying AWS ECR repo and pushing Docker Image To ECR

on:
  push:
    branches:
      - main

jobs:
  creation_of_ecr_repo:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

  pushing_docker_image:
    name: Pushing Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Create ECR Repository (if not exists)
        run: |
          aws ecr describe-repositories --repository-names test-nodejs-application || \
          aws ecr create-repository --repository-name test-nodejs-application

      - name: Get ECR Registry URI
        id: get-ecr-uri
        run: echo "ECR_REGISTRY=$(aws ecr describe-repositories --repository-names test-nodejs-application --query 'repositories[0].repositoryUri' --output text)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          ECR_REPOSITORY: test-nodejs-application
          IMAGE_TAG: awsecrimage:latest
        run: |
          docker build -t $ECR_REGISTRY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY:$IMAGE_TAG $ECR_REGISTRY:$IMAGE_TAG
          docker push $ECR_REGISTRY:$IMAGE_TAG

    
