name: Deploying ECS resources

on:
  workflow_run:
    workflows: ["push"]
    types: 
      - completed

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${secret.AWS_ACCESS_KEY}
          aws-secret-access-key: ${secret.AWS_SECRET_ACCESS_KEY}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd ECS
          terraform init

      - name: Terraform Plan
        run: |
          cd ECS 
          terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd ECS 
          terraform apply -auto-approve -input=false

